# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e928ae42857fbdf18df38ce83e968b4d1cd68827a230c3ab8dc484f3bfff613804496b303cc93a0dda6fb4232a4755669181bbee516bd00533f98b6c2a42593c

test:
  secret_key_base: 95795470ec1a829460277d1e9f60a3f55338b55002d0a84f6e9dab6b1d658312d41d5c85e29add1ad90f1febb3f38169ccd30618963fc72a351f15eb9d844e87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
